name: Merge Stage to Post Fork

on:
  push:
    branches:
      - stage

jobs:
  merge_stage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"

    - name: Switch to dev branch
      run: git switch ab/post_fork

    - name: Merge stage to post fork
      run: |
        git merge ${{ github.sha }} --no-commit --no-ff
        git commit -m 'merge stage to post fork'
